### ISSUE TITLE
Deprecated declarations in `io.github.kotools.assert`

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/assert#19]
## Description

Remove deprecated declarations in the package `io.github.kotools.assert`.

> This is a breaking change! 🔥

## Checklist

- [x] Remove deprecations.
- [x] Update `Work in progress` section in changelog.

**Comment by SanjaySiddharth** [comment]
Can i work on modifying the deprecated declarations in the given package?

**Comment by LVMVRQUXL** [comment]
> Can i work on modifying the deprecated declarations in the given package?

Of course @SanjaySiddharth ! Just fork the repository and make a pull request with your changes.
I will integrate them as soon as possible when working on the next major version. 😉

**Comment by LVMVRQUXL** [comment]
Done.
